### ISSUE TITLE
JSX Unable to import JS

### ISSUE THREAD

**Issue by Jbiloki** [keredson/bottle-react#31]
![image](https://user-images.githubusercontent.com/15188004/63228280-7cdaf600-c1a5-11e9-971e-0990cfa296ff.png)

Given JS files which export React Components I get errors thrown not allowing JSX to import the modules.

```
website            | [2019-08-18 17:44:49 +0000] [1] [INFO] Starting gunicorn 19.9.0
website            | [2019-08-18 17:44:49 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
website            | [2019-08-18 17:44:49 +0000] [1] [INFO] Using worker: sync
website            | [2019-08-18 17:44:49 +0000] [9] [INFO] Booting worker with pid: 9
website            | [2019-08-18 17:44:49 +0000] [10] [INFO] Booting worker with pid: 10
website            | [2019-08-18 17:44:49 +0000] [13] [INFO] Booting worker with pid: 13
website            | [2019-08-18 17:44:50 +0000] [15] [INFO] Booting worker with pid: 15
website            | [2019-08-18 17:44:50 +0000] [17] [INFO] Booting worker with pid: 17
website            | [2019-08-18 17:44:51 +0000] [10] [ERROR] Exception in worker process
website            | Traceback (most recent call last):
website            |   File "/usr/local/lib/python3.6/site-packages/react/jsx.py", line 43, in transform_string
website            |     '%s.transform' % self.JSX_TRANSFORMER_JS_EXPR, jsx, opts)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
website            |     return self._call(name, *args)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 92, in _call
website            |     return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 78, in _eval
website            |     return self.exec_(code)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
website            |     return self._exec_(source)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 88, in _exec_
website            |     return self._extract_result(output)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 167, in _extract_result
website            |     raise ProgramError(value)
website            | execjs._exceptions.ProgramError: Error: Parse Error: Line 4: Illegal import declaration
website            | 
website            | During handling of the above exception, another exception occurred:
website            | 
website            | Traceback (most recent call last):
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
website            |     worker.init_process()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
website            |     self.load_wsgi()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
website            |     self.wsgi = self.app.wsgi()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
website            |     self.callable = self.load()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
website            |     return self.load_wsgiapp()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
website            |     return util.import_app(self.app_uri)
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
website            |     __import__(module)
website            |   File "/usr/src/web/__init__.py", line 8, in <module>
website            |     br = BottleReact(app, prod=True)
website            |   File "/usr/local/lib/python3.6/site-packages/bottlereact.py", line 187, in __init__
website            |     transformer.transform(os.path.join(self.genned_path, jsx_hashed_fn), js_path=jsx_converted_fn, harmony=self.harmony)
website            |   File "/usr/local/lib/python3.6/site-packages/react/jsx.py", line 51, in transform
website            |     js = self.transform_string(i.read(), **kwargs)
website            |   File "/usr/local/lib/python3.6/site-packages/react/jsx.py", line 45, in transform_string
website            |     raise TransformError(str(e))
website            | react.jsx.TransformError: Error: Parse Error: Line 4: Illegal import declaration
website            | [2019-08-18 17:44:51 +0000] [10] [INFO] Worker exiting (pid: 10)
website            | [2019-08-18 17:44:51 +0000] [9] [ERROR] Exception in worker process
website            | Traceback (most recent call last):
website            |   File "/usr/local/lib/python3.6/site-packages/react/jsx.py", line 43, in transform_string
website            |     '%s.transform' % self.JSX_TRANSFORMER_JS_EXPR, jsx, opts)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
website            |     return self._call(name, *args)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 92, in _call
website            |     return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 78, in _eval
website            |     return self.exec_(code)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
website            |     return self._exec_(source)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 88, in _exec_
website            |     return self._extract_result(output)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 167, in _extract_result
website            |     raise ProgramError(value)
website            | execjs._exceptions.ProgramError: Error: Parse Error: Line 4: Illegal import declaration
website            | 
website            | During handling of the above exception, another exception occurred:
website            | 
website            | Traceback (most recent call last):
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
website            |     worker.init_process()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
website            |     self.load_wsgi()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
website            |     self.wsgi = self.app.wsgi()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
website            |     self.callable = self.load()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
website            |     return self.load_wsgiapp()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
website            |     return util.import_app(self.app_uri)
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
website            |     __import__(module)
website            |   File "/usr/src/web/__init__.py", line 8, in <module>
website            |     br = BottleReact(app, prod=True)
website            |   File "/usr/local/lib/python3.6/site-packages/bottlereact.py", line 187, in __init__
website            |     transformer.transform(os.path.join(self.genned_path, jsx_hashed_fn), js_path=jsx_converted_fn, harmony=self.harmony)
website            |   File "/usr/local/lib/python3.6/site-packages/react/jsx.py", line 51, in transform
website            |     js = self.transform_string(i.read(), **kwargs)
website            |   File "/usr/local/lib/python3.6/site-packages/react/jsx.py", line 45, in transform_string
website            |     raise TransformError(str(e))
website            | react.jsx.TransformError: Error: Parse Error: Line 4: Illegal import declaration
website            | [2019-08-18 17:44:51 +0000] [9] [INFO] Worker exiting (pid: 9)
website            | [2019-08-18 17:44:51 +0000] [13] [ERROR] Exception in worker process
website            | Traceback (most recent call last):
website            |   File "/usr/local/lib/python3.6/site-packages/react/jsx.py", line 43, in transform_string
website            |     '%s.transform' % self.JSX_TRANSFORMER_JS_EXPR, jsx, opts)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
website            |     return self._call(name, *args)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 92, in _call
website            |     return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 78, in _eval
website            |     return self.exec_(code)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
website            |     return self._exec_(source)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 88, in _exec_
website            |     return self._extract_result(output)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 167, in _extract_result
website            |     raise ProgramError(value)
website            | execjs._exceptions.ProgramError: Error: Parse Error: Line 4: Illegal import declaration
website            | 
website            | During handling of the above exception, another exception occurred:
website            | 
website            | Traceback (most recent call last):
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
website            |     worker.init_process()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
website            |     self.load_wsgi()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
website            |     self.wsgi = self.app.wsgi()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
website            |     self.callable = self.load()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
website            |     return self.load_wsgiapp()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
website            |     return util.import_app(self.app_uri)
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
website            |     __import__(module)
website            |   File "/usr/src/web/__init__.py", line 8, in <module>
website            |     br = BottleReact(app, prod=True)
website            |   File "/usr/local/lib/python3.6/site-packages/bottlereact.py", line 187, in __init__
website            |     transformer.transform(os.path.join(self.genned_path, jsx_hashed_fn), js_path=jsx_converted_fn, harmony=self.harmony)
website            |   File "/usr/local/lib/python3.6/site-packages/react/jsx.py", line 51, in transform
website            |     js = self.transform_string(i.read(), **kwargs)
website            |   File "/usr/local/lib/python3.6/site-packages/react/jsx.py", line 45, in transform_string
website            |     raise TransformError(str(e))
website            | react.jsx.TransformError: Error: Parse Error: Line 4: Illegal import declaration
website            | [2019-08-18 17:44:51 +0000] [13] [INFO] Worker exiting (pid: 13)
website            | [2019-08-18 17:44:51 +0000] [15] [ERROR] Exception in worker process
website            | Traceback (most recent call last):
website            |   File "/usr/local/lib/python3.6/site-packages/react/jsx.py", line 43, in transform_string
website            |     '%s.transform' % self.JSX_TRANSFORMER_JS_EXPR, jsx, opts)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
website            |     return self._call(name, *args)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 92, in _call
website            |     return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 78, in _eval
website            |     return self.exec_(code)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
website            |     return self._exec_(source)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 88, in _exec_
website            |     return self._extract_result(output)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 167, in _extract_result
website            |     raise ProgramError(value)
website            | execjs._exceptions.ProgramError: Error: Parse Error: Line 4: Illegal import declaration
website            | 
website            | During handling of the above exception, another exception occurred:
website            | 
website            | Traceback (most recent call last):
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
website            |     worker.init_process()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
website            |     self.load_wsgi()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
website            |     self.wsgi = self.app.wsgi()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
website            |     self.callable = self.load()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
website            |     return self.load_wsgiapp()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
website            |     return util.import_app(self.app_uri)
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
website            |     __import__(module)
website            |   File "/usr/src/web/__init__.py", line 8, in <module>
website            |     br = BottleReact(app, prod=True)
website            |   File "/usr/local/lib/python3.6/site-packages/bottlereact.py", line 187, in __init__
website            |     transformer.transform(os.path.join(self.genned_path, jsx_hashed_fn), js_path=jsx_converted_fn, harmony=self.harmony)
website            |   File "/usr/local/lib/python3.6/site-packages/react/jsx.py", line 51, in transform
website            |     js = self.transform_string(i.read(), **kwargs)
website            |   File "/usr/local/lib/python3.6/site-packages/react/jsx.py", line 45, in transform_string
website            |     raise TransformError(str(e))
website            | react.jsx.TransformError: Error: Parse Error: Line 4: Illegal import declaration
website            | [2019-08-18 17:44:51 +0000] [15] [INFO] Worker exiting (pid: 15)
website            | Traceback (most recent call last):
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 210, in run
website            |     self.sleep()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 360, in sleep
website            |     ready = select.select([self.PIPE[0]], [], [], 1.0)
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
website            |     self.reap_workers()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
website            |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
website            | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
website            | 
website            | During handling of the above exception, another exception occurred:
website            | 
website            | Traceback (most recent call last):
website            |   File "/usr/local/bin/gunicorn", line 10, in <module>
website            |     sys.exit(run())
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
website            |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 223, in run
website            |     super(Application, self).run()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
website            |     Arbiter(self).run()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 232, in run
website            |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 345, in halt
website            |     self.stop()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
website            |     time.sleep(0.1)
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
website            |     self.reap_workers()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
website            |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
website            | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
website            | [2019-08-18 17:44:51 +0000] [17] [ERROR] Exception in worker process
website            | Traceback (most recent call last):
website            |   File "/usr/local/lib/python3.6/site-packages/react/jsx.py", line 43, in transform_string
website            |     '%s.transform' % self.JSX_TRANSFORMER_JS_EXPR, jsx, opts)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
website            |     return self._call(name, *args)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 92, in _call
website            |     return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 78, in _eval
website            |     return self.exec_(code)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
website            |     return self._exec_(source)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 88, in _exec_
website            |     return self._extract_result(output)
website            |   File "/usr/local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 167, in _extract_result
website            |     raise ProgramError(value)
website            | execjs._exceptions.ProgramError: Error: Parse Error: Line 4: Illegal import declaration
website            | 
website            | During handling of the above exception, another exception occurred:
website            | 
website            | Traceback (most recent call last):
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
website            |     worker.init_process()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
website            |     self.load_wsgi()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
website            |     self.wsgi = self.app.wsgi()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
website            |     self.callable = self.load()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
website            |     return self.load_wsgiapp()
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
website            |     return util.import_app(self.app_uri)
website            |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
website            |     __import__(module)
website            |   File "/usr/src/web/__init__.py", line 8, in <module>
website            |     br = BottleReact(app, prod=True)
website            |   File "/usr/local/lib/python3.6/site-packages/bottlereact.py", line 187, in __init__
website            |     transformer.transform(os.path.join(self.genned_path, jsx_hashed_fn), js_path=jsx_converted_fn, harmony=self.harmony)
website            |   File "/usr/local/lib/python3.6/site-packages/react/jsx.py", line 51, in transform
website            |     js = self.transform_string(i.read(), **kwargs)
website            |   File "/usr/local/lib/python3.6/site-packages/react/jsx.py", line 45, in transform_string
website            |     raise TransformError(str(e))
website            | react.jsx.TransformError: Error: Parse Error: Line 4: Illegal import declaration
website            | [2019-08-18 17:44:51 +0000] [17] [INFO] Worker exiting (pid: 17)
```

**Comment by keredson** [comment]
are you trying to use an import polyfill or something?

**Comment by Jbiloki** [comment]
I am attempting to use https://github.com/amio/re-carousel, after npm installing and following their import instructions it seems I get an error not finding the resource:

> Uncaught ReferenceError: require is not defined

**Comment by keredson** [comment]
I designed this around pure JavaScript, not the nodejs variant, so require isn't defined without some other input.

For utilities like this, I've dumped them to vanilla js with tools like webpack.  For others (like material-ui) I've used the UMD versions.

**Comment by Jbiloki** [comment]
Thanks! I will try webpack first
