### ISSUE TITLE
OSError when installing from pip

### ISSUE THREAD

**Issue by jams2** [keredson/bottle-react#32]
When installing with `pip install bottle-react` on OSX (10.14.6), using python 3.6.0, I get the following error:

```
    ERROR: Command errored out with exit status 1:
     command: /Users/joshua/projects/horvath/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5z/ctnr4bfd3cjc_013l9fyvqs40000gn/T/pip-install-js3dg5kr/bottle-react/setup.py'"'"'; __file__='"'"'/private/var/folders/5z/ctnr4bfd3cjc_013l9fyvqs40000gn/T/pip-install-js3dg5kr/bottle-react/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/5z/ctnr4bfd3cjc_013l9fyvqs40000gn/T/pip-install-js3dg5kr/bottle-react/pip-egg-info
         cwd: /private/var/folders/5z/ctnr4bfd3cjc_013l9fyvqs40000gn/T/pip-install-js3dg5kr/bottle-react/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5z/ctnr4bfd3cjc_013l9fyvqs40000gn/T/pip-install-js3dg5kr/bottle-react/setup.py", line 16, in <module>
        version=__import__('bottlereact').__version__,
      File "/private/var/folders/5z/ctnr4bfd3cjc_013l9fyvqs40000gn/T/pip-install-js3dg5kr/bottle-react/bottlereact.py", line 62, in <module>
        libc = ctypes.CDLL("libc.so.6")
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 344, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: dlopen(libc.so.6, 6): image not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

This looks to be fixed in https://github.com/keredson/bottle-react/commit/5c3288dd1f918a2a754a5aab020ea101e00f2f68, but not merged into the release.

**Comment by bahijyamout** [comment]
Still getting this when trying to install on macOS Mojave, it seems the fix did not make it to the release ?
pip is getting bottle-react-16.2.4.tar.gz
