### ISSUE TITLE
python3 basestring not defined

### ISSUE THREAD

**Issue by keredson** [keredson/bottle-react#5]
```
Traceback (most recent call last):
  File "/home/derek/.local/lib/python3.5/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/derek/.local/lib/python3.5/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/derek/hvst/redesign/pyapp/lib/root.py", line 95, in root_path
    return hvst_root_path()
  File "/home/derek/hvst/redesign/pyapp/lib/root.py", line 86, in hvst_root_path
    return feed.exchange_feed_page()
  File "/home/derek/hvst/redesign/pyapp/lib/auth.py", line 227, in func_wrapper
    return func(*args, **kwargs)
  File "/home/derek/hvst/redesign/pyapp/lib/feed.py", line 393, in exchange_feed_page
    title='Dashboard - Harvest'
  File "/home/derek/.local/lib/python3.5/site-packages/bottlereact.py", line 191, in render_html
    react_js = react_node.to_javascript()
  File "/home/derek/.local/lib/python3.5/site-packages/bottlereact.py", line 263, in to_javascript
    ret.append(child.to_javascript())
  File "/home/derek/.local/lib/python3.5/site-packages/bottlereact.py", line 263, in to_javascript
    ret.append(child.to_javascript())
  File "/home/derek/.local/lib/python3.5/site-packages/bottlereact.py", line 264, in to_javascript
    elif isinstance(child, basestring):
NameError: name 'basestring' is not defined
```

**Comment by keredson** [comment]
fixed in 0.4.2.
